### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Daniel-Medeiros** [Orava2/hodlminer-binary#4]
Could you please add these features from cpuminer-opt so we can keep track of the current network difficulty and stratum difficulty?
![image](https://user-images.githubusercontent.com/7960317/42059991-3841875e-7b1d-11e8-87df-1d8c2acfab3a.png)
![image](https://user-images.githubusercontent.com/7960317/42060008-46d30324-7b1d-11e8-9802-b43a1d6f0a33.png)
very good miner

Thank you for your great work!

**Comment by Orava2** [comment]
Hi
I just stated to investigate this. I found the way to display block height and I'll try to get difficulty when I have time.

**Comment by Orava2** [comment]
I made a change that will print a block number and a difficulty when a new block is received. Pool difficulty is printed at the same time. I think that printing these values in a single line keep printings more compact but the new stratum/pool difficulty is not updated on the fly. You need to wait when a new block is found.

![kuva](https://user-images.githubusercontent.com/32876893/42591696-19a8ab14-8550-11e8-872b-fd773aa2aa64.png)

Would stratum/pool difficulty need a dedicated line?

**Comment by Daniel-Medeiros** [comment]
No need for a dedicated line, that would be easy to find it, looks good! :)
would you give them some colour to differentiate them? ;)

thank you so much!

**Comment by Orava2** [comment]
Here is the new version for testing http://hodlcoin.oo.fi/hodlminer-beta/hodlminer-avx2-2018v3_beta.exe

![kuva](https://user-images.githubusercontent.com/32876893/42734306-4969dab0-884a-11e8-99ec-24d7264df740.png)

The affinity parameter has changed. Use --affinity=1 to bind thread0 to cpu0, thread1 to cpu1 etc. --affinity=2 binds thread0 to cpu0, thread1 to cpu2, thread3 to cpu6. This can be used to bind threads to physical cores only.
